config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("finrepo.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("portfolio/", include("finrepo.portfolio.urls", namespace="portfolio")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

finrepo/portfolio/urls.py
from django.urls import path

from .views import (
    PortfolioCreateView,
    PortfolioListView, PortfolioUpdateView, PortfolioValueListView, PortfolioValueCreateView, PortfolioValueUpdateView
)

app_name = "portfolio"

urlpatterns = [
    path('', PortfolioListView.as_view(), name='portfolio_list'),
    path('create/', PortfolioCreateView.as_view(), name='portfolio_create'),
    path('update/<int:pk>/', PortfolioUpdateView.as_view(), name='portfolio_update'),
    path('<int:pk>/value/', PortfolioValueListView.as_view(), name='portfolio_value_view'),
    path('value/create/', PortfolioValueCreateView.as_view(), name='portfolio_value_create'),
    path('value/update/<int:pk>/', PortfolioValueUpdateView.as_view(), name='portfolio_value_update'),
]

finrepo/portfolio/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from djmoney.models.fields import MoneyField
from djmoney.money import Money


class Portfolio(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('portfolio:portfolio_list')


class PortfolioValue(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    balance = MoneyField(max_digits=16, decimal_places=2, default_currency='COP')
    added = MoneyField(max_digits=16, decimal_places=2, default_currency='COP', default=Money(0, 'COP'))
    date_added = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def get_absolute_url(self):
        return reverse_lazy('portfolio:portfolio_value_view', kwargs={'pk': self.portfolio_id})

finrepo/portfolio/forms.py
from django import forms
from django.forms import DateInput

from .models import Portfolio, PortfolioValue


class PortfolioForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = ['name', 'user']


class PortfolioValueForm(forms.ModelForm):
    class Meta:
        model = PortfolioValue
        fields = ["portfolio", 'balance', 'added', 'date_added']
        widgets = {
            'date_added': DateInput(attrs={'type': 'date'}),
        }

finrepo/portfolio/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from djmoney import settings
from djmoney.contrib.exchange.models import convert_money

from .forms import PortfolioForm, PortfolioValueForm
from .models import Portfolio, PortfolioValue


class PortfolioListView(ListView):
    model = Portfolio
    context_object_name = 'portfolio_list'
    queryset = Portfolio.objects.all().select_related('user')


class PortfolioCreateView(CreateView):
    model = Portfolio
    form_class = PortfolioForm


class PortfolioUpdateView(UpdateView):
    model = Portfolio
    form_class = PortfolioForm


class PortfolioValueListView(DetailView):
    model = Portfolio
    context_object_name = 'portfolio'
    template_name = 'portfolio/portfolio_value_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['portfolio_value_list'] = PortfolioValue.objects.filter(
            portfolio=self.object
        ).select_related('portfolio').order_by('-date_added')
        context['portfolio_value_list_json'] = [
            {
                'date_added': portfolio_value.date_added,
                'balance': convert_money(portfolio_value.balance, settings.DEFAULT_CURRENCY).amount,
                'added': convert_money(portfolio_value.added, settings.DEFAULT_CURRENCY).amount
            }
            for portfolio_value in context['portfolio_value_list']
        ]
        return context


class PortfolioValueCreateView(CreateView):
    model = PortfolioValue
    form_class = PortfolioValueForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PortfolioValueUpdateView(UpdateView):
    model = PortfolioValue
    form_class = PortfolioValueForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

finrepo/portfolio/templates/portfolio/portfolio_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}
  {% block head_title %}
    PortFolio
  {% endblock head_title %}
{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="row">
        {% for field in form %}
            <div class="col-md-12">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                {% if field.errors %}
                    {% render_field field class+="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class+="form-control" %}
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <br>
    <div class="row">
        <div class="col-md-12">
            <button type="submit" class="btn btn-primary">Send</button>
        </div>
    </div>
</form>
{% endblock %}

finrepo/portfolio/templates/portfolio/portfolio_list.html
{% extends "base.html" %}
{% block title %}
  {% block head_title %}
    PortFolio
  {% endblock head_title %}
{% endblock title %}

{% block content %}
<div class="row">
  <div class="col">
    <a class="btn btn-primary" href="{% url "portfolio:portfolio_create" %}" role="button">Create Portfolio</a>
  </div>
</div>
<div class="row">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">User</th>
    </tr>
  </thead>
  <tbody>

      {% for portfolio in portfolio_list %}
        <tr>
          <td>
            <a href="{% url "portfolio:portfolio_value_view" portfolio.id %}">{{ portfolio.name }}</a>
          </td>
          <td>{{ portfolio.user }}</td>
          <td>
            <a class="btn btn-primary" href="{% url "portfolio:portfolio_update" portfolio.id %}" role="button">Update</a>
          </td>
        </tr>
      {% endfor %}

  </tbody>
</table>
</div>
{% endblock %}

finrepo/portfolio/templates/portfolio/portfolio_value_list.html
{% extends "base.html" %}
{% block title %}
  {% block head_title %}
    PortFolio
  {% endblock head_title %}
{% endblock title %}

{% block content %}
<div class="row">
  <div class="col">
    <a class="btn btn-primary" href="{% url "portfolio:portfolio_value_create" %}" role="button">Create Valor Portfolio</a>
  </div>
</div>
<div class="row">
  <div class="col">
   <canvas id="grow"></canvas>
  </div>
  <div class="col">
   <canvas id="gains"></canvas>
  </div>
</div>
<div class="row">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">PortFolio</th>
      <th scope="col">Balance</th>
      <th scope="col">Added</th>
      <th scope="col">Add to</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for portfolio_value in portfolio_value_list %}
    <tr>

        <td>
          {{ portfolio_value.portfolio.name }}
        </td>
        <td>{{ portfolio_value.balance }}</td>
        <td>{{ portfolio_value.added }}</td>
        <td>{{ portfolio_value.date_added }}</td>
        <td>
          <a class="btn btn-primary" href="{% url "portfolio:portfolio_value_update" portfolio_value.id %}" role="button">Update</a>
        </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock content %}
{% block inline_javascript %}
  {{ portfolio_value_list_json|json_script:"portfolio_value" }}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.6.2/chart.min.js" integrity="sha512-tMabqarPtykgDtdtSqCL3uLVM0gS1ZkUAVhRFu1vSEFgvB73niFQWJuvviDyBGBH22Lcau4rHB5p2K2T0Xvr6Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const ctx_grow = document.getElementById('grow').getContext('2d')
      const ctx_gains = document.getElementById('gains').getContext('2d')
      const data = JSON.parse(document.getElementById("portfolio_value").textContent)
      data.reverse()
      const labels = []
      const data_balance = [{
        label: 'Balance',
        data: [],
      },{
        label: 'Balance Without Added',
        data: [],
      }]
      const data_gains = [{
        label: 'Actual vs Before',
        data: [],
      },{
        label: 'Actual vs Initial',
        data: [],
      }]
      let accumulator = 0
      data.forEach((item, index)=>{
        labels.push(item.date_added)
        const balance = item.balance
        const balance_without_added = item.balance - item.added
        const win = balance_without_added - parseFloat(index>0?data[index-1].balance:item.balance)
        const win_2 = balance_without_added - parseFloat(data[0].balance) - parseFloat(accumulator)
        accumulator += parseFloat(item.added)
        console.log(accumulator, index)
        data_balance[0].data.push(balance)
        data_balance[1].data.push(parseFloat(balance_without_added))
        data_gains[0].data.push(win)
        data_gains[1].data.push(win_2)
      })
      const context =[{ctx: ctx_grow, datasets: data_balance}, {ctx: ctx_gains, datasets: data_gains}]
      context.forEach((item)=>{
        console.log(item)
        new Chart(item.ctx, {
          type: 'line',
          data: {
            labels: labels,
            datasets: item.datasets
          }
        })
      })

    })
  </script>
{% endblock inline_javascript %}

finrepo/portfolio/templates/portfolio/portfoliovalue_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}
  {% block head_title %}
    PortFolio
  {% endblock head_title %}
{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="row">
        {% for field in form %}
            <div class="col-md-12">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                {% if field.errors %}
                    {% render_field field class+="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class+="form-control" %}
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <br>
    <div class="row">
        <div class="col-md-12">
            <button type="submit" class="btn btn-primary">Send</button>
        </div>
    </div>
</form>
{% endblock %}